[book]
authors = ["Will Duquette"]
language = "en"
src = "src"
title = "Joe v0.9.0 User's Guide"

[build]
build-dir = "../../docs"          # the directory where the output is placed
create-missing = false            # whether or not to create missing pages
use-default-preprocessors = true  # use the default preprocessors

[output.html.fold]
enable = true
level = 1
